import { EventType, IncrementalSource, MouseInteractions } from 'rrweb';

export const be = {
   FullSnapshot: EventType.FullSnapshot,
    IncrementalSnapshot: EventType.IncrementalSnapshot,
    Meta: EventType.Meta,
     Mutation: IncrementalSource.Mutation,
        MouseMove: IncrementalSource.MouseMove,
       MouseInteraction: IncrementalSource.MouseInteraction,
        Scroll: IncrementalSource.Scroll,
        ViewportResize: IncrementalSource.ViewportResize,
       Input: IncrementalSource.Input,
        TouchMove: IncrementalSource.TouchMove,
         MediaInteraction: IncrementalSource.MediaInteraction,
         StyleSheetRule: IncrementalSource.StyleSheetRule,
         CanvasMutation: IncrementalSource.CanvasMutation,
          Font: IncrementalSource.Font,
         Log: IncrementalSource.Log,
        Drag: IncrementalSource.Drag,
         StyleDeclaration: IncrementalSource.StyleDeclaration,
        Selection: IncrementalSource.Selection,
       AdoptedStyleSheet: IncrementalSource.AdoptedStyleSheet,
         MouseUp: MouseInteractions.MouseUp,
        MouseDown: MouseInteractions.MouseDown,
        Click: MouseInteractions.Click,
        ContextMenu: MouseInteractions.ContextMenu,
        DblClick: MouseInteractions.DblClick,
        Focus: MouseInteractions.Focus,
        Blur: MouseInteractions.Blur,
        TouchStart: MouseInteractions.TouchStart,
        TouchMove_Departed: MouseInteractions.TouchMove_Departed,
        TouchEnd: MouseInteractions.TouchEnd,
        TouchCancel: MouseInteractions.TouchCancel,
}